name: Deploy FastAPI to AWS EC2 on Release

on:
  release:
    types: [published]  # Déclenche le workflow lors de la publication d'une release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      
      - name: Build Docker image
        run: docker build -t dl-tikimind .

     
      - name: Save Docker image to tar
        run: docker save dl-tikimind > dl-tikimind.tar

     
      - name: Clean up server space
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Supprimer les anciens conteneurs et images Docker
            docker system prune -af
            # Nettoyer les fichiers temporaires
            sudo rm -rf /tmp/*
            sudo rm -rf /home/ubuntu/deploy/*.tar
            # Nettoyer les logs
            sudo journalctl --vacuum-size=50M
            # Nettoyer les paquets
            sudo apt-get autoremove -y
            sudo apt-get clean
            # Vérifier l'espace disponible
            df -h


      - name: Upload Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: dl-tikimind.tar
          target: /home/ubuntu/deploy/

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /home/ubuntu/deploy
            docker load < dl-tikimind.tar
            docker rm -f deeplearn-tikimind || true
            docker run -d \
              --name deeplearn-tikimind \
              -p 8000:8000 \
              deeplearn-tikimind